version: '3'

services:
  reverse-proxy:
    image: jwilder/nginx-proxy
    container_name: reverse-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  reverse-proxy-acme:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: reverse-proxy-acme
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=reverse-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/etc/nginx/certs
      - ./vhost.d:/etc/nginx/vhost.d
      - ./html:/usr/share/nginx/html

  texttoaudio-app:
    image: texttoaudio-app
    container_name: texttoaudio-app
    restart: always
    environment:
      - VIRTUAL_HOST=texttoaudio.shopabcquocdat.xyz
      - LETSENCRYPT_HOST=texttoaudio.shopabcquocdat.xyz
      - LETSENCRYPT_EMAIL=quocdattranhuu1606@gmail.com
    expose:
      - "8501"
