BEARER_TOKEN = ""
WEBHOOK_URL = "https://n8n.srv819221.hstgr.cloud/webhook/docsQdrantv1111"
OPENAI_API_KEY = "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"